version: '3.8'

services:
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-car_reviews}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-12345678}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    networks:
      - car_reviews

  worker:
    depends_on:
      - database
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8000:8000"
    networks:
      - car_reviews

volumes:
  database_data:

networks:
  car_reviews: